name: "debug_evals"
dump_dir: /home1/09753/hprairie/scratch/mamba/130m_eval_testing/base3/0000010000
ckpt_dir: /home1/09753/hprairie/scratch/mamba/130m/base3/checkpoints/0000010000
generator:
  max_tokens: 8192
  dtype: bf16
  temperature: 1.0
  top_p: 0.95
harness:
  tasks:
    - wikitext 
    # - task: boolq
    #   dataset_kwargs:
    #     trust_remote_code: true
    # - task: nq_open
    #   num_fewfixeshot: 5
  # - piqa
  # - siqa
  # - tqa
  # - winogrande
  # - obqa
  # - arc_easy
  # - arc_challenge
  # - race_middle
  # - race_high
  # - gsm8k
  # - bbh
  # - copa
  # - human_eval_plus
  # - mbpp
  # - mmlu
