name: "debug_evals"
# ckpt_dir: !!CHANGETHIS!!
# dataset_dir: !!CHANGETHIS!!
# dump_dir: !!CHANGETHIS!!
tasks: wikitext 
generator:
  compile_prefilling: false
  reduce_generation_overhead: false
  max_tokens: 8192
  dtype: bf16
