# Template config, need to change dump_dir, data.root_dir and tokenizer.path

dump_dir: /home1/09753/hprairie/scratch/mamba/130m-ft/full
name: "mamba130m"
steps: 1_000
probe_freq: null #100
grad_acc_steps: 16

seed: 777
optim:
  lr: 6.0e-4
  weight_decay: 0.1
  warmup: 200
  lr_min_ratio: 0.00001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: true
  tp_size: 1

model:
  dim: 768
  n_heads: 24
  n_groups: 24
  state_dim: 128
  conv_size: 4
  n_layers: 24
  bias: false
  conv_bias: true
  dt_bias: true
  D_has_head_dim: false
  learnable_init_states: false
  ffn_dim_multiplier: 1
  init_args:
    A_init_min: 0.01
    A_init_max: 2

data:
  root_dir: /home1/09753/hprairie/scratch/data-shuffled
  sources:
    wikitext1: 100.0
  batch_size: 4
  prefetch_size: 1024
  seq_len: 2048
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: huggingface
    path: EleutherAI/gpt-neox-20b

profiling:
  run: true

checkpoint:
  init_ckpt_path: /home1/09753/hprairie/scratch/weights/mamba/mamba2-130m/spliced_lingua_distributed_pytorch_model
  dump:
    every: 100
    keep: 100
  eval:
    every: 5000
    keep: 100

logging:
  freq: 1

async_eval_gpus: 8
